# Generated by Django 4.2.20 on 2025-04-21 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_car_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_on']},
        ),
    ]
