# Generated by Django 4.2.20 on 2025-04-23 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0007_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='car',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_cars', to=settings.AUTH_USER_MODEL),
        ),
    ]
