# Generated by Django 4.2.20 on 2025-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['brand'], name='car_car_brand_f1c6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['model'], name='car_car_model_42d024_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['title'], name='car_car_title_ae874b_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['category'], name='car_car_categor_afca6b_idx'),
        ),
    ]
