# Generated by Django 4.2.20 on 2025-05-03 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_car_car_car_brand_f1c6dc_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+999999999'.Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
