# Generated by Django 4.2.20 on 2025-04-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='read',
            field=models.IntegerField(choices=[(0, 'Not Read'), (1, 'Read')], default=0),
        ),
    ]
